on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: portfoliomanagementacr.azurecr.io
        username: ${{ secrets.acr_portfoliomanagementacr_username }}
        password: ${{ secrets.acr_portfoliomanagementacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t portfoliomanagementacr.azurecr.io/dailysharepricecluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push portfoliomanagementacr.azurecr.io/dailysharepricecluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_dailysharepricecluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep dailymutualfundb724 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace dailymutualfundb724`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: dailymutualfundb724
        container-registry-url: portfoliomanagementacr.azurecr.io
        container-registry-username: ${{ secrets.acr_portfoliomanagementacr_username }}
        container-registry-password: ${{ secrets.acr_portfoliomanagementacr_password }}
        secret-name: dailyshareprdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: dailymutualfundb724
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          portfoliomanagementacr.azurecr.io/dailysharepricecluster:${{ github.sha }}
        imagepullsecrets: |
          dailyshareprdockerauth
